### ISSUE TITLE
How to temporary disable 500 Internal Server Error

### ISSUE THREAD

**Issue by webclubz** [giuscris/formwork#119]
Hello Giuseppe.
Can you please tell me or show me the way how to temporary disable this Internal Server Error 500 for debugging?

**Comment by giuscris** [comment]
Hello Economou, thank you for using Formwork.

You could comment these lines to disable the error view:

https://github.com/getformwork/formwork/blob/99feae73072d39584eef77bc133b28b4f219542a/formwork/src/Formwork.php#L97

https://github.com/getformwork/formwork/blob/99feae73072d39584eef77bc133b28b4f219542a/formwork/src/Admin/Admin.php#L57

Tell me if all of this work.

**Comment by webclubz** [comment]
Yep its ok for me ;) Now i can see a detailed error message. 

Thank you!

**Comment by giuscris** [comment]
I've just added to the `2.x` branch the possibility to opt-out the error handlers by adding the following line to `site/config/system.yml` (see PR https://github.com/getformwork/formwork/pull/124):
```yaml
errors.set_handlers: false
```
Thank you for suggesting me this.

**Comment by webclubz** [comment]
> I've just added to the `2.x` branch the possibility to opt-out the error handlers by adding the following line to `site/config/system.yml` (see PR #124):
> 
> ```yaml
> errors.set_handlers: false
> ```
> 
> Thank you for suggesting me this.

That's great! You're always welcome Giuseppe, have a nice day.
