### ISSUE TITLE
Published after rename Blog Slug

### ISSUE THREAD

**Issue by MiFrance** [giuscris/formwork#20]
Just change "Blog" title to "Articles" and save.
After rename "blog" Slug to "articles" and save again.
1 post is Unpublished and impossible to change status to "Published".

**Comment by giuscris** [comment]
I tried the steps but don't get the issue. Could you please post the content of the affected pages?

**Comment by MiFrance** [comment]
Oops, I'm not saying anything.
I had added an end of publication for March 18th (it is already midnight lol)
