### ISSUE TITLE
Not published but routable

### ISSUE THREAD

**Issue by MiFrance** [giuscris/formwork#25]
For a page, there is a behavior of confusion when he defined as unpublished but available.
I thought that configured so, we would have access to the page by knowing its URL, but would not be displayed in the menu.
Well no, it sends me on the 404 page

**Comment by giuscris** [comment]
Please don't confuse page status with page visibility. If a page is not published then it isn't neither routable nor visible. Not routable pages are pages used internally like the not found (error 404) page, which cannot be directly reached but is still necessary to the system.
If you're wondering how to make pages invisible from the menu, currently the only way to do this is to remove the number prefix from the page folder. For example, if I want to hide the page Typography, which folder name is `3-typography`, I have just to rename the folder to `typography`. Actually this is quite confusing and complex to do everytime.
Thanks for the feedback, I'll add a way to set page visibility in the Admin Panel.

**Comment by MiFrance** [comment]
Thank you for the clarification.
So in fact routable means "system page".
Thank you for the tip to put a page not visible in the menu ;)
Formwork is awesome!

**Comment by MiFrance** [comment]
Other question, Not published = Draft ?

**Comment by giuscris** [comment]
Yes, you can think that's like a draft.
Please don't change any language string, it would break the consistency across the translations. I think it's rather clean and understandable.

**Comment by MiFrance** [comment]
Not precisely, that's why I'm refining the translation.
Another example with the role "User", the best would be "Editor".

**Comment by MiFrance** [comment]
[fr.yml.zip](https://github.com/giuscris/formwork/files/2978933/fr.yml.zip)

**Comment by giuscris** [comment]
Your translation is really useful but please don't use issues to post your translations, Pull requests are there for a reason. Make a PR and we'll discuss about the changes you propose.
However I'm not going to accept "Draft" instead of "Not published". The content of language strings should reflect their names, which in this case is `page.status.not-published`, and have to be consistent with other translations.

**Comment by giuscris** [comment]
> Thanks for the feedback, I'll add a way to set page visibility in the Admin Panel.

Done in last commit b92e10c.
