### ISSUE TITLE
Use author and description string in layout

### ISSUE THREAD

**Issue by MiFrance** [giuscris/formwork#26]
https://github.com/giuscris/formwork/blob/b92e10cc1bf71989f4752bc1d225199ee58f193d/templates/layouts/site.php#L6
After this line add:
```
	<?php if ($site->description()): ?>    
	<meta name="description" content="<?= $site->description() ?>">
	<?php endif;?>	
	<?php if ($site->author()): ?>    
	<meta name="author" content="<?= $site->author() ?>">
	<?php endif;?>	
```

**Comment by giuscris** [comment]
Hi @MiFrance, I apreciate you're contributing to the default templates! But please note that Issues are not appropriate for these kind of changes, use Pull Request instead so we can discuss and apply the changes when you're done. Thanks.
