### ISSUE TITLE
Add tags posts

### ISSUE THREAD

**Issue by MiFrance** [giuscris/formwork#27]
If possible to add this function for blog posts?
Is great with the same input allowed extension in options panel style.
<img width="1029" alt="Capture d’écran 2019-03-23 à 23 50 23" src="https://user-images.githubusercontent.com/12760053/54872582-772fde80-4dc6-11e9-92fd-01fdd213f9e9.png">

**Comment by giuscris** [comment]
Sure, it will be included in the default template enhancements already planned. Thank you for the suggestion!
