### ISSUE TITLE
[bug] Pagination

### ISSUE THREAD

**Issue by MiFrance** [giuscris/formwork#30]
Hi @giuscris ,
I created 6 blog posts, I donate the active paging and if I click on page 2, I am automatically redirected to the 404 page.
`//localhost/formwork/blog/page/2/`
Pagination setting is by default ie 5 items per page.

**Comment by giuscris** [comment]
Hi, did you upgrade from 0.10.1 to 0.10.2 from the Administratiom panel? Template schemes changed too, but they’re excluded from updates from the panel to not accidentally overwrite user modifications.

**Comment by MiFrance** [comment]
That's right, I upgraded from the admin panel.
I just downloaded from the git and this will immediately better.
It is thus solved ;)

**Comment by giuscris** [comment]
Yes, in previous versions every URI that ended in `/page/*/` was valid and was routed to the page itself. Now only pages which specify `type: listing` in their scheme are allowed to have `/page/*/` and `/tag/*/` in the URI.
