### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by drez25** [giuscris/formwork#358]
hello,
I followed the installation manual for linux and windows and I get the following error:
[Mon Sep 12 10:18:58 2022] 10.100.102.28:57152 [500]: GET / - Uncaught Error: Class "Requiement" not found in /home/test/soosyze/bootstrap/requirements.php:3
Stack trace:
#0 /home/test/soosyze/index.php(7): require_once()
#1 {main}
  thrown in /home/test/soosyze/bootstrap/requirements.php on line 3

please advise.

Dan

**Comment by giuscris** [comment]
Hello Dan,
I think you're not writing about Formwork, there is no "bootstrap/requirements.php" here.
