### ISSUE TITLE
Panel : Editor

### ISSUE THREAD

**Issue by Wemago** [giuscris/formwork#513]
When trying to edit a page I'm getting this error.

![Captura de ecrã 2024-05-13 210346](https://github.com/getformwork/formwork/assets/135612/3dac5b9c-5022-4f9e-8f24-c632467cd0c6)

**Comment by giuscris** [comment]
It seems strange to me, I've added buttons to navigate to previous and next siblings in the page editor.
Are you on a fresh install? I can't replicate this situation.

**Comment by Wemago** [comment]
Yes, it was on a fresh install.

**Comment by giuscris** [comment]
I'm sorry. I've tried with a new install and I couldn't replicate the problem.
As I can see you're on Windows, maybe the problem is only on these system.
I need to investigate more.

**Comment by giuscris** [comment]
Resolved with https://github.com/getformwork/formwork/commit/f56ccaee0608ce145d5e663e113cd1a437cc63ec

Page paths were mishandled on Windows due to different directory separator, so the current page was missing in the inclusive siblings.
