### ISSUE TITLE
admin

### ISSUE THREAD

**Issue by ncopz** [giuscris/formwork#68]
How can I rename the admin folder for security?

**Comment by Wemago** [comment]
You can change it on config file.
Look at formwork/defaults.php and you'll see admin -> root.

**Comment by ncopz** [comment]
How to align center images in markdown?
And I also don't see any align center/left/ right icon in the editor.

Preview (eye icon) not working, does not match the edited/new post.

**Comment by Wemago** [comment]
Honestly I'm don't have big knowledge on markdown, maybe project owner @giuscris can have an answer for that.

The preview icon does work, the page needs to be routable.

**Comment by ncopz** [comment]
Yes, you are right. The page needs to be routable.

Now I have a new problem and I just found out earlier. Yesterday I only tried formwork from xampp only and because I like this project, then I tried installing it on one of my domains. Once installed, I was surprised by not being able to access the admin page, every time I go to the domain page, I always return to the home page.

**Comment by Wemago** [comment]
I've only worked with formwork on local, so I haven't got a clue about that, but it should work since I'm using local domains with SSL. Your error can be related to a config url or something like that. Did you modify the htaccess?

Do you know laragon? It's a really good alternative for xampp.

**Comment by ncopz** [comment]
I know Laragon but have never tried it.

I didn't modify anything in it, after I took it from composer (composer create-project getformwork/formwork) then I uploaded it.

This is the domain that I installed Formwork but the admin page can't be accessed.
https://aquarius.click

**Comment by Wemago** [comment]
Do you have admin set for true on the config file?
I'm trying to figure out a way to debug it.

**Comment by ncopz** [comment]
Yes and after uploading it then accessing the admin page I just need to create a new username and password?

I've also tried other hosting but the results are still the same.

**Comment by Wemago** [comment]
You only create the user if it's a fresh installation.
I need to check if I have a spare space on one of my domains to do some testing.

On your domain is it a fresh installation?

**Comment by ncopz** [comment]
Of course, I do it from ..

**With Composer**
If you prefer to install the latest stable release of Formwork with Composer you can use this command:

$ composer create-project getformwork/formwork
Composer_ will create a formwork folder with a fresh ready-to-use Formwork installation.

**Comment by giuscris** [comment]
> Yes, you are right. The page needs to be routable.
> 
> Now I have a new problem and I just found out earlier. Yesterday I only tried formwork from xampp only and because I like this project, then I tried installing it on one of my domains. Once installed, I was surprised by not being able to access the admin page, every time I go to the domain page, I always return to the home page.

@ncopz for security reasons you can register a new user only from `localhost` because in remote hosting the first one who can access the admin panel can register itself.

**Comment by ncopz** [comment]
> > Yes, you are right. The page needs to be routable.
> > Now I have a new problem and I just found out earlier. Yesterday I only tried formwork from xampp only and because I like this project, then I tried installing it on one of my domains. Once installed, I was surprised by not being able to access the admin page, every time I go to the domain page, I always return to the home page.
> 
> @ncopz for security reasons you can register a new user only from `localhost` because in remote hosting the first one who can access the admin panel can register itself.

You mean, I create a new user + password from localhost and then upload it to my hosting?

**Comment by ncopz** [comment]
Now I can access the admin page.
What can I do now if I delete a registered user from localhost? Or are there two people left in it?

Thank you @giuscris 

![work](https://user-images.githubusercontent.com/26650405/109180272-45e39880-77bd-11eb-9bbd-e975ca2d5369.png)

**Comment by wsokc** [comment]
> > Yes, you are right. The page needs to be routable.
> > Now I have a new problem and I just found out earlier. Yesterday I only tried formwork from xampp only and because I like this project, then I tried installing it on one of my domains. Once installed, I was surprised by not being able to access the admin page, every time I go to the domain page, I always return to the home page.
> 
> @ncopz for security reasons you can register a new user only from `localhost` because in remote hosting the first one who can access the admin panel can register itself.

How to do this without localhost capabilities ?

**Comment by Imerion** [comment]
I also wonder how to do this without running from localhost. I have seen a solution in other similar CMS systems where the first user registering after installation gets to download a file which should be uploaded to the server and only after that will it be possible to log in with that user. That will ensure only a person with access to the server can create a new user.

**Comment by wsokc** [comment]
@ncopz 

can you share a dummy file for us to use please ?

**Comment by ncopz** [comment]
> I also wonder how to do this without running from localhost. I have seen a solution in other similar CMS systems where the first user registering after installation gets to download a file which should be uploaded to the server and only after that will it be possible to log in with that user. That will ensure only a person with access to the server can create a new user.

It can, and I've done it and it works. And I also modified the script code according to my wishes. (nirvanaholic.com)

**Comment by ncopz** [comment]
> > > Yes, you are right. The page needs to be routable.
> > > Now I have a new problem and I just found out earlier. Yesterday I only tried formwork from xampp only and because I like this project, then I tried installing it on one of my domains. Once installed, I was surprised by not being able to access the admin page, every time I go to the domain page, I always return to the home page.
> > 
> > 
> > @ncopz for security reasons you can register a new user only from `localhost` because in remote hosting the first one who can access the admin panel can register itself.
> 
> How to do this without localhost capabilities ?

Using two users during the first installation and I'm using it successfully till now for nirvanaholic.com

**Comment by giuscris** [comment]
Hello everyone,

I'm considering different options to let user register from remote, obviously I want to keep it secure.

@Imerion it's a good idea what you've mentioned about other systems, I think I'll make an implementation like this.

Since also @wsokc asked, currently you can first register in `localhost`, then you can copy to remote the file `admin/acoounts/<yourusername>.yml` at the same location.

Thank you for your interest in Formwork.

**Comment by Imerion** [comment]
@giuscris Sounds great! And thanks for your work on this project - it looks very interesting and I would really like to try it out some more.
